# Generated by Django 5.0.3 on 2024-07-01 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('address', models.TextField(default='', max_length=1000)),
                ('staffs_num', models.IntegerField()),
                ('num_of_beds', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('patient_name', models.CharField(default='', max_length=200)),
                ('contact_number', models.CharField(default='', max_length=200, unique=True)),
                ('department', models.CharField(default='', max_length=200)),
                ('disease', models.CharField(default='', max_length=200)),
                ('patient_address', models.CharField(default='', max_length=200)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='hospital_app.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('hospital_visits', models.DateField()),
                ('doctor_name', models.CharField(default='', max_length=200)),
                ('patient_status', models.CharField(default='', max_length=200)),
                ('medicine', models.CharField(default='', max_length=100)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalname', to='hospital_app.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patientname', to='hospital_app.patient')),
            ],
        ),
    ]
