# Generated by Django 5.0.3 on 2024-03-13 07:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('address', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('patient_name', models.CharField(default='', max_length=200)),
                ('doctor_name', models.CharField(default='', max_length=200)),
                ('department', models.CharField(default='', max_length=200)),
                ('disease', models.CharField(default='', max_length=200)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='catalog.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='PatientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_checkup', models.TextField(default='', max_length=1000)),
                ('consultation', models.TextField(default='', max_length=1000)),
                ('admitted', models.BooleanField(default=False)),
                ('discharged', models.BooleanField(default=False)),
                ('referred', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patientstatus', to='catalog.patient')),
            ],
        ),
    ]
