# Generated by Django 5.0.3 on 2024-03-12 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('register_id', models.UUIDField(default=uuid.uuid4, help_text='Registration id for hospitals', primary_key=True, serialize=False)),
                ('hosp_name', models.CharField(max_length=200, unique=True)),
                ('staff_number', models.IntegerField()),
                ('address', models.CharField(max_length=200, unique=True)),
                ('numb_beds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, help_text='patients id', primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=200, unique=True)),
                ('contact_number', models.CharField(max_length=200)),
                ('doctor_name', models.CharField(max_length=200)),
                ('dept_name', models.CharField(default='Surgery Department', max_length=200)),
                ('patient_disease', models.CharField(max_length=200)),
                ('primary_check', models.DateTimeField()),
                ('medicine', models.CharField(max_length=200, null=True)),
                ('consultation', models.DateTimeField()),
                ('admitted', models.DateTimeField(blank=True, null=True)),
                ('referred', models.BooleanField()),
                ('discharged', models.DateTimeField(blank=True, null=True)),
                ('hospital_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.hospital')),
            ],
        ),
    ]
