# Generated by Django 5.0.3 on 2024-03-18 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisit',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitalname', to='catalog.hospital'),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='medicine',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patientname', to='catalog.patient'),
        ),
    ]
